### ISSUE TITLE
Calendar (google?) for the course

### ISSUE THREAD

**Issue by vincenzocoia** [UBC-STAT/stat545.stat.ubc.ca#23]
@sciclic had a great idea about posting a calendar of deadlines (originally appearing in [this comment](https://github.com/UBC-STAT/stat545.stat.ubc.ca/pull/15#discussion_r463198597)). Should consider having this. Perhaps also for class meetings and office hours.

**Comment by vincenzocoia** [comment]
Embed a calendar on a webpage like this: https://ubc-mds.github.io/calendar/ -- Team Sonja?

**Comment by sciclic** [comment]
I created a calendar on Google and exported it into zip format, with proposed deadlines for all submissions: (1) Lecture worksheets (6 total), (2) Mini Project Milestones (3 total), and (3) Team Troubleshooting Assignments (3 total). Please let me know what you think! I kept all deadlines to Fridays (11:59pm I suppose?) and only had to add an extra one on a Monday so that they could all fit, but I think Team Troubleshooting Assignments should be designed to only last 1 hour so that should still meet the 6hr/week I believe. 

Please find it here: [STAT545A.ical.zip](https://github.com/UBC-STAT/stat545.stat.ubc.ca/files/5101281/STAT545A.ical.zip), I think it should automatically download!

**Comment by sciclic** [comment]
Actually, I also included class meetings, but no office hours yet since that hasn't been discussed!

**Comment by vincenzocoia** [comment]
This looks great!

- There are 4 Team Troubleshooting assignments listed (not 3), meaning we can delete that Monday deadline. This leaves 2 hours per week on non-worksheet projects. I made this change. 
- I also added a schedule for the videos to be launched
- I added STAT 545B classes

[STAT545.ics.zip](https://github.com/UBC-STAT/stat545.stat.ubc.ca/files/5119564/STAT545.ics.zip)

**Comment by sciclic** [comment]
Looks great! I think it's ready to go on the website.
