### ISSUE TITLE
Course Topics

### ISSUE THREAD

**Issue by vincenzocoia** [UBC-STAT/stat545.stat.ubc.ca#25]
@sciclic Let's do this: by next Thursday (Aug 13), let's both come up with some ideas about how we think the topics for STAT 545 should change. Then we can talk about these in more detail on that meeting, and talk about arranging these.

**Comment by sciclic** [comment]
I went through both the current STAT545 guidebook & Jenny Bryan's STAT545 website as inspiration to think of an order for the topics - we can discuss further in this week's meeting, but my idea with changing the first two lectures around is that if submissions this year will be done primarily through Canvas, and the idea with GitHub is that they use it for the collaborative troubleshooting assignment, I think that getting students set up with RStudio and teaching a few R basics might make more sense to start with. This way, the GitHub lecture would also allocate time to get students to meet their collaborative troubleshooting partner, and give them time to work through a teamwork document. 

As for the remaining proposed topics, I have changed the order of the data wrangling & ggplot lectures - I still think it would make sense to alternate them, but starting off with data wrangling seems more natural in my opinion. In addition, I was wondering whether it would make sense to add tidy data to the ggplot part II lecture, or at least have them be consecutive because I feel like they may somewhat overlap. Lastly, I moved the file input/output to the end; I think that it could be introduced to students through additional resources or pre-reading in Canvas, but given that none of the assignments actually require it as a skill / have it as a learning objective, it could be explored in more detail in STAT545B if reading in datasets is a learning objective.

In fact, I was thinking that perhaps we could remove the file input/output lecture altogether and instead have a "choose a topic" slot instead; since it's the last lecture, I thought it may be interesting to have a choice of 3 topics and ask students to vote what they would like to learn far enough in advanced to design those materials - which would allow to personalize their learning experience. The long term idea could be that each year you would have an additional lecture that students have chosen, and those could be accessed through the STAT545 website too! However, I am not familiar with the course design requirements at UBC so I have no clue if it's doable, but I thought I would share the idea in case,

1. Introduction to STAT545 + Introduction to R (Sept 10th)
2. Git, GitHub & Version Control (Sept 15th)
3. R Markdown & Reproducibility (Sept 17th) - *in place of authoring* 
4. Data wrangling: Part I (Sept 22nd)
5. ggplot2: Part I (Sept 24th)
6. Data wrangling: Part II (Sept 29th)
7. ggplot2: part II & tidy data (Oct 1st)
8. Working with factors in R (Oct 6th)
10. Tibble joins (Oct 8th)
11. Effective visualizations (Oct 13th)
10. The Model-Fitting Paradigm in R (Oct 15th)
12. File input/output (Oct 20th)

I look forward to discussing!

Thank you,
Icíar

**Comment by vincenzocoia** [comment]
@sciclic 's modifications are looking good to me. Here's a brain dump of current ideas and notes from last year's Instructor's repo -- I still need to think about ordering of topics. 

545A

- Lecture 1 on R: students can work directly on the browser using [GitHub Classroom](https://github.blog/2020-05-26-code-in-the-browser-with-github-classroom/).
- File I/O: add `here::here()`, and perhaps googlesheets, googledocs, readxl packages because I suspect many students will be using Google Drive as well.
- `dplyr` is changing. Change teaching of `_if`, `_at`, `_all` scoped variants to using [`across()`](https://www.tidyverse.org/blog/2020/04/dplyr-1-0-0-colwise/).
- Holding discussions via pull requests needs to show up.
- More focus on nesting and list columns (I can check my analyses to see where they are most useful, perhaps working with model objects).
- tsibbles

545B

- Exception handling (`try()`) with functions. Perhaps even `withTimeout()`.
- Continuous Integration (with Travis? GitHub Actions?)
- Bash scripting (students struggled with this whenever they needed to use it. Useful for git, and for interacting with text files. Also for Makefiles.)
- docker (or just in general, environment management)
- bookdown, for writing a thesis?
- blogdown, for making a website? This might be a stretch -- not really related to data analysis.
- shinytest package for testing shiny apps?
- Remove getting data from the web (scraping and API's)

**Comment by vincenzocoia** [comment]
OK, part 2 of my brainstorming and note hunting.

1\. Introduction to STAT545 + Introduction to R (Sept 10th)
2\. Git, GitHub & Version Control (Sept 15th)
    - Add collaboration through pull requests and Issues. 
    - (is this too packed of a lecture?)
3\. R Markdown & Reproducibility (Sept 17th) - *in place of authoring* 
4\. Data wrangling: Part I (Sept 22nd)
    - Add "making tibbles"
5\. ggplot2: Part I (Sept 24th)
6\. Data wrangling: Part II (Sept 29th)
    - Add scoped variants of `summarise()` and `mutate()`, with `across()` (requires a very up-to-date version of dplyr).
7\. ggplot2: part II & ~~tidy data~~ __effective vis__ (Oct 1st)
__8\. tidy data__ (Oct 6th)
~~8\.~~ 9\. __Special data types__: Working with factors in R __& dates and times__ (Oct 8th)
~~9\.~~ 10\. Tibble joins (Oct 13th)
~~10\. Effective visualizations (Oct 15th)~~ 
11\. The Model-Fitting Paradigm in R (Oct 15th)
12\. File input/output (Oct 20th)
    - here::here(), and perhaps googlesheets, googledocs, readxl packages
__13\. Choose your own adventure__

Here's why I'm thinking of these changes:

### Swapping of pivoting and effective vis

- ggplot2 Part II lecture was boring two years ago, and last year I think I ended early and failed to tackle previous problems with the remaining time. But on the same token, Part I tends to overflow.
- I'm on the fence about whether effective graphing should take up an entire lecture, because it just feels like a laundry list of do's and don'ts. Not effective to go over a list like this in lecture, because it won't be digested. I'd rather empower students to feel that they have agency to craft a message and creatively graph it.

> In addition, I was wondering whether it would make sense to add tidy data to the ggplot part II lecture

I don't know whether pivoting and tidy data would fit in half a lecture. I'm thinking that, if Effective Vis is shortened to half a lecture, it might make more sense to put it here than tidy data. But I agree that tidy data is highly related -- the question is, can they get away with two graphing lectures without pivoting data? I think we might be able to get away with it.

### Wrangling I and II

I remember Data wrangling Part I being slow and dry, and Part II being packed as I tried to get to the "interesting" stuff:
    - Moved dates and times, tsibbles, and implicit NA's for another lecture.  
    - Moved "making tibbles" to Part I.

### Factors

I don't think factors are that important that we should dedicate a whole lecture to it. 

I also think dates and times need some handling, but don't take up a full lecture, either.

Since both are special types of data, perhaps it makes sense to put them together. 

### Choose your own adventure

> remove the file input/output lecture altogether and instead have a "choose a topic" slot instead

I counted 13 lectures. In which case, we don't have to remove a topic at all.

I like this idea. @sciclic do you have ideas as to how it would work? Especially in a way that doesn't step on the toes of 545B.

**Comment by vincenzocoia** [comment]
Also @sciclic -- additional, general comments are definitely welcome. I certainly have blind spots in developing this that you can see around.

**Comment by sciclic** [comment]
### General notes

+ I think the **overall outline** looks great as you've proposed it; I agree that **effective visualizations** felt awkward as a lecture of its own and it's best to add it to the ggplot lecture. While it's true that tidy data would also work with ggplot, the tidy data lecture worksheet can still include ggplot features since students would already be familiar with them from their previous lecture - the goal of the worksheet could actually be to apply the tidy data principles to ggplot, which would highlight to students how useful it is for data viz after 2 ggplot lectures without it!

+ I would maybe **move the model fitting lecture prior to the tibble joins**, I actually went through last year's class worksheet and it think it would fit perfectly - we don't really have to go into statistics, but I think the basics of linear regression are very easy to understand and I'm certain that this will come in handy for almost everyone taking the class - we could provide resources for those who want to look deeper into statistics, but just provide a high-level overview in class!

+ **Wrangling I and II** make more sense now - I agree that "working with factors" is probably not enough for a whole lecture, so adding dates & times, tsibbles and NAs to those lectures and making the "special data types" lecture that you suggest will also be more interesting for students while evening out the content between wrangling I and II. 

+ Adding **here::here** is definitely a great idea, we learnt about it in STAT547 last year and I wish I would've known from the moment I started using R!

+ For the **choose your own adventure**, I'm thinking maybe suggest some of these topics (but definitely open to suggestions because I'm not sure what would fit a lecture, just thinking of ideas that may interest students):
   + Build a personal website using GitHub pages (or at least get started?) 
   + Making slides in R Markdown with xaringan (could be a reduced version of [this workshop](https://arm.rbind.io/slides/xaringan.html#1))
   + A greater look at linear regression modelling? Not sure if this fits the scope of the course, wouldn't go super deep into statistics either but could maybe delve deeper into the broom package.
   + Ten random useful things about R that you may not know about (there are many interesting articles along these lines that show cool packages or R Markdown functionalities: [example 1](https://towardsdatascience.com/ten-random-useful-things-in-r-that-you-might-not-know-about-54b2044a3868), [example 2](https://www.analyticsvidhya.com/blog/2019/04/8-useful-r-packages-data-science/), [example 3](https://medium.com/@alearrigo/the-most-underrated-r-packages-254e4a6516a1)) 

### Proposed outline

Additions in **bold**, removals in ~~strikethrough~~.

1. Introduction to STAT545 + Introduction to R (Sept 10th)
2. Git, GitHub & Version Control (Sept 15th) - *more notes + ideas for this lecture on #29*
- ~~(is this too packed of a lecture?)~~ **I don't think so if we follow a similar outline as below!**
- **"GitHub for cloud storage"** as pre-work: register for GitHub + set up a repo
- **"GitHub for collaboration"** as lecture: in-class demo and explanations.
- **"GitHub for collaboration: Activity"** by (1) briefly introduce collaborative troubleshooting assignment and (2) setting up the repo will their assignments for the project will live. Also doubles as students getting to chat with their project partner in breakout rooms.
3. R Markdown & Reproducibility (Sept 17th) - in place of authoring
- **Remove Rmd presentations? **Also discussed in #29, my thought is that it's too brief to fully understand & not many students may use it - if they have a particular interest it can instead be offered as a lecture of its own in the "choose your own adventure" slot.
- **Leaves space if anything from last lecture "spills over".**
4. Data wrangling: Part I (Sept 22nd)
- Add "making tibbles"
5. ggplot2: Part I (Sept 24th)
6. Data wrangling: Part II (Sept 29th)
- Add scoped variants of summarise() and mutate(), with across() (requires a very up-to-date version of dplyr).
7. ggplot2: part II & tidy data effective vis (Oct 1st)
8. Tidy data (Oct 6th)
9. **The Model-Fitting Paradigm in R** (Oct 15th)
10. Special data types: Working with factors in R & dates and times (Oct 8th)
11. Tibble joins (Oct 13th)
12. File input/output (Oct 20th)
- here::here(), and perhaps googlesheets, googledocs, readxl packages
13. Choose your own adventure

**Comment by vincenzocoia** [comment]
A big **YES** to all of these things!

**Comment by almas2019** [comment]
Hi @vincenzocoia  I was wondering what you all of think of potentially incorporating some of these R stats illustrations into our Worksheets , they are under CC license https://github.com/allisonhorst/stats-illustrations. Lots of great tidyverse, here package and other illustration examples

**Comment by vincenzocoia** [comment]
Looks great, thanks @almas2019 ! Let's refer to this when we're building that week's content (I think it's Week 3).
