### ISSUE TITLE
Week 05A Guidance

### ISSUE THREAD

**Issue by dy-lin** [UBC-STAT/stat545.stat.ubc.ca#64]
hey @vincenzocoia,

do you have any recommended readings or anything you'd like in week 05a guidance? I'll be starting tomorrow

**Comment by dy-lin** [comment]
In class today you mentioned that you had ideas about how to reorganize the weekly guidance page. Since I haven't started on the page yet, we could implement them this week. What are the ideas? @vincenzocoia

**Comment by vincenzocoia** [comment]
Now that I think of it, stat545.com wouldn't be appropriate for Week 5, because it uses the outdated `gather` and `spread` functions, and doesn't have anything on the model-fitting paradigm.

I think there's a pivot vignette with the tidyr package that's helpful -- I think that should be required. I'm not sure about the model-fitting paradigm. I think maybe a basic `broom` vignette if there is one.

I can add resources before the merge happens if need be.

> you mentioned that you had ideas about how to reorganize the weekly guidance page.

Yeah, I was thinking of moving the lecture details out and making those have their own page. We can make another section on the course "dashboard" stat545.stat.ubc.ca/course that's a table of lecture names and numbers, with a link to a page per lecture -- perhaps even replacing that large table at the bottom of the course dashboard. The weekly guidance would be like a to-do list for the week.

> we could implement them this week. 

OK, I think that's the fire I need to get started with this. I'll work on the Week 5 branch, perhaps even sometime today (depending on whether I get the next video script down on time).

**Comment by dy-lin** [comment]
Alright, I'll start working on the guidance using the old format so at least we'll have the content to convert into the new format once we get that started

**Comment by dy-lin** [comment]
See #65 pull request for content

**Comment by dy-lin** [comment]
I've updated the quick lookup table on the course dashboard, but haven't actually linked the Week 5 Guidance page under weekly guidance since nobody has commented a review yet, and that the video links are still missing
